### PR TITLE
Setup of Civic Victory Theme 🎨

### PR DESCRIPTION
**Pull request by danieltomasku**
This PR sets up the `CivicVictoryTheme`, which can be imported into all Victory Chart components for consistent styling and color palette. This setup will help us get the ball rolling for adding the correct Civic colors, fonts, etc. I added the `CivicVictoryTheme` into the bar-chart to show an example of how to import and implement. 
Some things to note:
- This branch is branched off from the `feature-barchart` branch.
- None of the correct colors are implemented in the theme, except for Light Plum. So we will need to come back and fill in the colors based on the style guide.
- This is not meant to be a final implementation, merely an initial setup. All feedback is welcome, including suggestions on variable names, code styling, file locations, etc! 😃 

screen shot 2018-05-02 at 9 24 25 pm

### CODE REVIEW

**Comment by jaronheard** [comment]
My review for this is going to be somewhat high level - I'm intentionally not doing a detailed review, but just inspecting to make sure that the patterns we're establishing in this PR are generally in line with how we'd like the data visualization components to work.

[ x ] Shows basic implementation of a Bar Chart using VictoryCharts in the Storybook
[ x ] Implementing common VictoryTheme file that can be evolved
[ x ] Logical structure in terms of files and component library

I'm cool with getting this merged and evolving it from there but going to defer to @DingoEatingFuzz if he'd like to do a more detailed review before merging.

**Comment by DingoEatingFuzz** [comment]
I strongly agree with merging a less than perfect theme and following up with a detailed review and iteration.

Having the theme in the master branch will help with the creation of all our other VictoryChart-based components.

**Comment by jaronheard** [comment]
@DingoEatingFuzz yes, I'll open up a new issue with some more review and todos. I'll let you merge this. I saw a red box on the Travis check at one point, just want to make sure it doesn't break anything.

**Comment by danieltomasku** [comment]
Thank you for the feedback @DingoEatingFuzz ! I just pushed up some changes addressing your comments. Not sure why Travis is failing. This branch is branched off from `feature-barchart` which looks like had some failing commits to begin with. Anyway, this is ready for re-review whenever you get a chance!

**Comment by jaronheard** [comment]
I made an effort to fix the build issues that we were addressing... we will see if it works. When I tried to build the whole project from this branch I saw these errors:
```Module not found: Error: Can't resolve 'victory' in '/Users/jaronheard/Documents/programming/web/hackoregon2018/civic/packages/component-library/dist/BarChart'```

```Module not found: Error: Can't resolve 'victory-core' in '/Users/jaronheard/Documents/programming/web/hackoregon2018/civic/packages/component-library/dist/BarChart'```

There was some issues with the naming not being consistent across the Component / Storybook / Story, I renamed everything to HorizontalBarChart to be consistent.

**Comment by jaronheard** [comment]
Well, unfortunately that didn't fix anything.

**Comment by DingoEatingFuzz** [comment]
So the root cause of the Travis failure is webpack taking more than 10 minutes to build while not writing anything to stdout. At that point Travis assumes something went wrong.

One of the builds in the matrix did manage to build one package before timing out:

image

All those ms add up to 9m46s, which is pretty good evidence that webpack is timing out sometimes (most times, apparently) while building packages.

Since this didn't happen before, it can be assumed that it's due to adding VictoryCharts as a dependency. I am no webpack expert, but I think most of the added time can be attributed to code splitting and dead code elimination throughout all the added files (which includes all of VictoryCharts dependencies as well, such as d3.

In #92 I am removing `yarn build` from Travis since it's mostly wasteful. The only packages that have to be built are `mock-wrapper` and `component-library`. This makes the build much faster and removes the possibility of webpack timing out.

It would be cool to figure out faster ways to make webpack build at some point.

**Comment by DingoEatingFuzz** [comment]
I normally don't commandeer branches, but I wanted to get this merged so people working on other charts can build on this during the buildathon.

Great work, @danieltomasku!

**Pull request merged**
