### PR TITLE
Major Dependency Updates

### PR DESCRIPTION
**Pull request by jaronheard**
## What's been done?
Major dependency updates:
- [x] Node 8 -> Node 10
- [x] Webpack 2 -> 3
- [x] Webpack 3 -> 4
- [x] Babel 6 -> 7
- [x] Storybook 3 -> 4
- [x] React 15 -> 16
- [x] Emotion 9 -> 10
- [x] Deck.gl 4 -> 6
- [x] react-map-gl 3-> 4

Other fun:
1. Tweaked Prettier settings and ESLint rules.
2. Added packages/component-library/es to .gitignore
3. Fixed a bunch of linting errors in the component-library. Also added a mix of deprecation warnings and temporarily disabled ESLint on some components (mostly Sandbox UI).

### Bad things ☠️
**Must Fix**
- [x] HMR not working in project packages

**Should Fix**
- [x] HeatMap component story is broken, due to a combination of the MapGL and Storybook upgrades
- [x] 2017 Packages broken due to Recharts

### Not great things 🤷‍♂️
- [x] Really annoying error message every time you launch a dev server ```✖ ｢wdm｣: ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.```

### Good things 🙌
- All other tests pass, all packages build and run, storybook works

Next steps (probably in an additional PR):
- Cleaning codebase with Prettier and ESLint, and adding enforcement
- Eliminate excess dependencies, and extract dev-dependencies to workspace root
- Add lint scripts to all packages to enable yarn lint from root
- Storybook 4 -> 5
-  Reimplement Geocoder in Disaster Resilience

Put on the back burner:
- [x] HMR improvements - currently HMR works for some specific cases but does not work consistently across the board. After much research, my determination is that implementing React Hot Loader is not worthwhile at present, it's too buggy for class components. Story Cards don't hot-reload properly, and I'd rather have something stable. See these issues on React Hot Loader [1138](https://github.com/gaearon/react-hot-loader/issues/1138)  [1196](https://github.com/gaearon/react-hot-loader/issues/1196) and [this article](https://codeburst.io/react-hot-loader-considered-harmful-321fe3b6ca74).

### CODE REVIEW

**Comment by jaronheard** [comment]
I merged in #431, because otherwise we ended up with a bunch of Map stories being broken. This is tantalizingly close to being ready to merge. 

If someone wants to tag in to see if they can resolve any of the "bad things" listed in the original issue, that would be amazing!

**Comment by mendozaline** [comment]
I was able to fix the HeatMap story. It was an issue with the storybook select knob. Should I push the changes to this branch?

**Comment by jaronheard** [comment]
@mendozaline Yes please!

**Comment by jaronheard** [comment]
Woo hoo! HMR is now working. Developer experience, improved!

There are just a few bad things remaining, and I'm kind of tempted to apply temporary workarounds for those issues so we can release this update, and move on to cleaning up the codebase with ESLint and Prettier.

The most vexing issue is the 2017 Recharts components. Unfortunately, our current version of Recharts isn't compatible with React 16, and the updated version of Recharts has breaking API changes for our current charts. Given that we plan to migrate the 2017 components to our current components very soon, fixing the charts seems like a waste of time. However, in order to migrate the 2017 components, we want to have this update merged, but we want a working version of the 2017 components to reference. Not sure what the right way forward is on this.

**Comment by jaronheard** [comment]
@DingoEatingFuzz Made the fixes you suggested. If you take a final look and it's all good, you can go ahead and merge.

**Pull request merged**
