### PR TITLE
Feature/add transportation

### PR DESCRIPTION
**Pull request by DavideDaniel**

### CODE REVIEW

**Comment by clemf** [comment]
@DavideDaniel Is this ready to merge? I'm getting this error when running `npm start` in the package:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by DavideDaniel** [comment]
after running `npm run bootstrap`?

**Comment by clemf** [comment]
Yes, I followed the instructions you made in the readme. I ran `nvm use`, then `npm install` which runs bootstrap. I'm seeing this same `babel-node` error with emergency response.

**Comment by DavideDaniel** [comment]
fixed now - we're gonna want to use yarn to make sure we have the same npm client across machines.. using yarn workspaces now

**Comment by meganmckissack** [comment]
@DavideDaniel tried to run transportation package but getting an error message: failed at start:dev script 'cross-env NODE_ENV=development babel-node server'.  In know we're supposed to set the env variables for some packages, I checked the scripts in the package.json and it seemed to be correct compared to the other packages so I'm not sure where I should be setting the variable.

**Comment by DavideDaniel** [comment]
we should actually not set the env variables outside of these scripts.. in fact we'll want to normalize around how the envs are set so that they don't vary from project to project... so when I run `npm start` in transportation folder everything just runs for me.. try doing a `yarn bootstrap` at the root, then `npm start` at the transportation directory. We can normalize this behavior in upcoming changes to use `npx` to use the hoisted packages.

**Comment by meganmckissack** [comment]
I get this error when running npm start `Local package.json exists, but node_modules missing, did you mean to install?`

**Comment by DavideDaniel** [comment]
Yea I was just illustrating that the app should start without errors. You don't install in the local dir. Bootstrap from root or if you have lerna installed globally, `lerna bootstrap` from anywhere and then `npm start` from transport dir

**Comment by MikeTheCanuck** [comment]
I started running through the README from the `master` branch today to refresh myself on where this project stands.  I filed a bunch of bugs for WARNings still being thrown, then remembered that this PR is a major blocker and probably has a lot of fixes.  (Feel free to leave those bugs aside until after the PRs get merged, and I'll re-check for them after the merges, closing any that no longer apply).

I'm following the [README included in this PR](https://github.com/hackoregon/civic/blob/49a349ad364d2804644e53deae015fc599baa0a2/README.md) and I notice a large number of "unmet peer dependency" `warnings` when I run `git pull`, `git checkout feature/addTransportation`, `nvm use` then `yarn bootstrap`:

```
[3/4] 🔗  Linking dependencies...
warning " > url-loader@0.5.9" has unmet peer dependency "file-loader@*".
warning "@hackoregon/civic-server > @hackoregon/component-library > react-leaflet@1.7.4" has unmet peer dependency "prop-types@^15.5.0".
warning " > @storybook/addon-actions@3.2.15" has unmet peer dependency "react@*".
warning " > @storybook/addon-actions@3.2.15" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-actions > react-inspector@2.2.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > @storybook/addon-info@3.2.15" has unmet peer dependency "react@*".
warning "@storybook/addon-info > @storybook/components@3.2.15" has unmet peer dependency "react@*".
warning "@storybook/addon-info > @storybook/components@3.2.15" has unmet peer dependency "react-dom@*".
warning " > @storybook/addon-knobs@3.2.15" has unmet peer dependency "react@*".
warning " > @storybook/addon-knobs@3.2.15" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-knobs > react-datetime@2.10.3" has unmet peer dependency "react@>=0.13".
warning "@storybook/addon-knobs > react-datetime@2.10.3" has unmet peer dependency "react-dom@>=0.13".
warning "@storybook/addon-knobs > react-textarea-autosize@5.2.0" has unmet peer dependency "react@>=0.14.0 <17.0.0".
warning "@storybook/addon-knobs > react-datetime > react-onclickoutside@6.7.0" has unmet peer dependency "react@^15.5.x || ^16.x".
warning "@storybook/addon-knobs > react-datetime > react-onclickoutside@6.7.0" has unmet peer dependency "react-dom@^15.5.x || ^16.x".
warning " > @storybook/addon-links@3.2.15" has unmet peer dependency "react@*".
warning " > @storybook/addon-links@3.2.15" has unmet peer dependency "react-dom@*".
warning " > @storybook/addon-notes@3.2.15" has unmet peer dependency "react@*".
warning " > @storybook/react@3.2.15" has unmet peer dependency "react@>=15.0.0 || ^16.0.0".
warning " > @storybook/react@3.2.15" has unmet peer dependency "react-dom@>=15.0.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui@3.2.15" has unmet peer dependency "react@*".
warning "@storybook/react > @storybook/ui@3.2.15" has unmet peer dependency "react-dom@*".
warning "@storybook/react > babel-preset-react-app@3.1.0" has unmet peer dependency "babel-runtime@^6.23.0".
warning "@storybook/react > @storybook/ui > @storybook/react-fuzzy@0.4.3" has unmet peer dependency "react@^0.14.7 || ^15.0.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-icons@2.2.7" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-icons@2.2.7" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-komposer@2.0.0" has unmet peer dependency "react@^0.14.7 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-modal@3.1.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16".
warning "@storybook/react > @storybook/ui > react-modal@3.1.2" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16".
warning "@storybook/react > @storybook/ui > react-treebeard@2.1.0" has unmet peer dependency "react@^15.5.4 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard@2.1.0" has unmet peer dependency "react-dom@^15.5.4 || ^16.0.0".
warning "@storybook/react > @storybook/ui > mantra-core > react-komposer@1.13.1" has unmet peer dependency "react@^0.14.3 || ^15.0.0".
warning "@storybook/react > @storybook/ui > mantra-core > react-simple-di@1.2.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-icons > react-icon-base@2.1.0" has unmet peer dependency "react@*".
warning "@storybook/react > @storybook/ui > react-icons > react-icon-base@2.1.0" has unmet peer dependency "react-dom@*".
warning "@storybook/react > @storybook/ui > react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
warning "@storybook/react > @storybook/ui > react-komposer > react-stubber@1.0.0" has unmet peer dependency "react@^0.14.7 || ^15.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard > radium@0.19.6" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard > velocity-react@1.3.3" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning "@storybook/react > @storybook/ui > react-treebeard > velocity-react@1.3.3" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning " > chai-enzyme@0.6.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
warning " > chai-enzyme@0.6.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
warning "chai-enzyme > react-element-to-jsx-string@5.0.7" has unmet peer dependency "react@^0.14.8 || ^15.0.1".
warning " > enzyme@2.9.1" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
warning " > react-addons-test-utils@15.6.2" has unmet peer dependency "react-dom@^15.4.2".
warning "react-hot-loader > redbox-react@1.5.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning "react-hot-loader > redbox-react@1.5.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-budget > recharts@0.22.4" has unmet peer dependency "react-transition-group@^1.1.2".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/component-library > react-selectize@2.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/component-library > react-selectize@2.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/component-library > eslint-import-resolver-webpack@0.7.1" has unmet peer dependency "eslint-plugin-import@>=1.4.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/component-library > react-addons-css-transition-group@15.6.2" has unmet peer dependency "react@^15.4.2".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > react-fontawesome@1.6.1" has unmet peer dependency "react@>=0.12.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > react-player@0.15.0" has unmet peer dependency "react@*".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools@3.4.1" has unmet peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools@3.4.1" has unmet peer dependency "react-redux@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools@3.4.1" has unmet peer dependency "redux@^3.5.2".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools-dock-monitor@1.1.2" has unmet peer dependency "react@^0.14.9 || ^15.3.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools-log-monitor@1.4.0" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-form@6.8.0" has unmet peer dependency "react@^15.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-form@6.8.0" has unmet peer dependency "react-redux@^4.3.0 || ^5.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-form@6.8.0" has unmet peer dependency "redux@^3.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-homelessness > react-helmet@5.2.0" has unmet peer dependency "react@>=15.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools-dock-monitor > react-dock@0.2.4" has unmet peer dependency "react@>=0.13.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools-log-monitor > react-json-tree@0.11.0" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning "workspace-aggregator-09d400c6-d05b-4c4e-b78a-ae0d0abf2482 > @hackoregon/civic-emergency-response > redux-devtools-log-monitor > react-json-tree@0.11.0" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0".
```

**Comment by MikeTheCanuck** [comment]
Next, when I open a new `Terminal` shell and run `yarn watch` from the civic directory I see this Error:

```
$ yarn watch
yarn run v1.3.2
$ node scripts/watch
/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

Error: [BABEL] /Users/mike/code/HackOregon/civic/packages/civic-babel-presets/index.js: Couldn't resolve extends clause of /Users/mike/code/HackOregon/civic/.babelrc in base
    at Logger.error (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at ConfigChainBuilder.mergeConfig (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:186:32)
    at buildConfigChain (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:64:11)
    at OptionManager.init (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transformFileSync (/Users/mike/code/HackOregon/civic/node_modules/babel-core/lib/api/node.js:152:10)
    at babelMe (/Users/mike/code/HackOregon/civic/scripts/watch.js:34:10)
    at babelify (/Users/mike/code/HackOregon/civic/scripts/watch.js:45:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MikeTheCanuck** [comment]
Next, when I run `yarn start` from the first shell session for the `emergency-response` package, then browse to http://localhost:3000/, the server dies and throws this error:

```
$ yarn start
yarn run v1.3.2
$ npm-run-all --parallel test:watch start:dev
$ npm run test -- --watch
$ cross-env NODE_ENV=development babel-node server
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start:dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MikeTheCanuck** [comment]
Next, when I run `yarn start` from the `homelesness` package and browse to http://localhost:3000/, the browser receives "Not Found" as an HTML response and the server has reported this output:

```
$ yarn start
yarn run v1.3.2
$ npm-run-all --parallel test:watch start:dev
$ npm run clean
$ npm run test -- --watch

> @hackoregon/civic-homelessness@1.0.0-alpha.1c62c05f test /Users/mike/code/HackOregon/civic/packages/homelesness
> mocha --opts ./mocha.opts 'src/**/*.test.js' "--watch"


> @hackoregon/civic-homelessness@1.0.0-alpha.1c62c05f clean /Users/mike/code/HackOregon/civic/packages/homelesness
> rimraf build && mkdir build

$ cross-env NODE_ENV=development babel-node server
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.

Server ready ✓


=====================================

Access application at:
http://localhost:3000

=====================================

CTRL-C to exit the process
    
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
[mochawesome] Generating report files...



  <App />
Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.
    ✓ should render its children

  <NotFound />
    ✓ should render the Page Not Found text

  request
    stubbing successful response
      ✓ should format the response correctly
    stubbing error response
      ✓ should catch errors
(node:35332) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]


  4 passing (73ms)


[mochawesome] Report saved to reports/mochawesome/mochawesome.html


webpack built 436232227b9e8977ab71 in 9817ms

ERROR in ./src/components/HomelessPopulation/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library/lib/Dropdown/Dropdown' in '/Users/mike/code/HackOregon/civic/packages/homelesness/src/components/HomelessPopulation'
 @ ./src/components/HomelessPopulation/index.js 26:16-78
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev
```

**Comment by MikeTheCanuck** [comment]
Next when I run `yarn start` from the `housing` package, the server reports the following output:

```
$ yarn start
yarn run v1.3.2
$ npm-run-all --parallel test:watch start:dev
$ npm run test -- --watch
$ npm run clean

> @hackoregon/civic-housing@1.0.0-alpha.1c62c05f test /Users/mike/code/HackOregon/civic/packages/housing
> cross-env BABEL_ENV=test mocha --opts ./mocha.opts 'src/**/*.test.js' "--watch"


> @hackoregon/civic-housing@1.0.0-alpha.1c62c05f clean /Users/mike/code/HackOregon/civic/packages/housing
> rimraf build && mkdir build

$ cross-env BABEL_ENV=development babel-node server
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.

Server ready ✓


=====================================

Access application at:
http://localhost:3000

.
.
.

  111 passing (152ms)


[mochawesome] Report saved to reports/mochawesome/mochawesome.html


webpack built 7948946a50a1d087c793 in 7260ms

ERROR in ./src/components/App/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library/lib/Dropdown/Dropdown' in '/Users/mike/code/HackOregon/civic/packages/housing/src/components/App'
 @ ./src/components/App/index.js 24:16-78
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/DemographicDetailView/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library/lib/RechartsPie/RechartsPie' in '/Users/mike/code/HackOregon/civic/packages/housing/src/components/DemographicDetailView'
 @ ./src/components/DemographicDetailView/index.js 11:19-87
 @ ./src/components/App/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/Map/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library/lib/LeafletMap/LeafletMap' in '/Users/mike/code/HackOregon/civic/packages/housing/src/components/Map'
 @ ./src/components/Map/index.js 13:18-84
 @ ./src/components/App/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev
```

**Comment by MikeTheCanuck** [comment]
Finally when I run `yarn start` from `transportation` package, my request to http://localhost:3000/ responds in Chrome with a blank page.  I looked at the console and found three errors:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Root)
    in div (created by Root)
    in Provider (created by Root)
    in Root
```

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.
    at invariant (webpack:////Users/mike/code/HackOregon/civic/~/fbjs/lib/invariant.js?:42)
    at instantiateReactComponent (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/instantiateReactComponent.js?:72)
    at instantiateChild (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/ReactChildReconciler.js?:42)
    at eval (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/ReactChildReconciler.js?:69)
    at traverseAllChildrenImpl (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/traverseAllChildren.js?:75)
    at traverseAllChildrenImpl (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/traverseAllChildren.js?:91)
    at traverseAllChildren (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/traverseAllChildren.js?:170)
    at Object.instantiateChildren (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/ReactChildReconciler.js?:68)
    at ReactDOMComponent._reconcilerInstantiateChildren (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/ReactMultiChild.js?:183)
    at ReactDOMComponent.mountChildren (webpack:////Users/mike/code/HackOregon/civic/~/react-dom/lib/ReactMultiChild.js?:222)
```

```
Uncaught TypeError: Cannot read property '_renderedComponent' of undefined
    at getData (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:57)
    at window.addEventListener (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:191)
```

**Comment by MikeTheCanuck** [comment]
:( I was hoping that I would be able to help fix some of the issues that I've observed in trying to validate this PR.  After reviewing last night and this morning, I am unable to figure out what is the solution to any of the errors I observed.  Sorry folks - but if anyone has any ideas, I'd be happy to investigate further.

**Comment by jaronheard** [comment]
@DavideDaniel I tried following the instructions in the README of the `feature/addTransportion` branch and replicated the 5 errors that @MikeTheCanuck mentioned above.

**Comment by DavideDaniel** [comment]
Yeah the problem is that they were using different versions of the component library.. now that everything is inside and using the current one those lib paths are wrong. I have changes in different branches that solve this.. so once we get this merged we can follow fast with others but this has been languishing here..

**Comment by jaronheard** [comment]
I'm ok with merging this and then merging #23 and #24 if someone wants to give me review access

**Pull request merged**
