### PR TITLE
Fix all packages

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Two major things are achieved with this:

1. All project packages now have a working `yarn start` command that will bring up the dev site relatively in tact. Some small css issues are left, but most of it has been shaken out.

2. `yarn build` from the root successfully invokes `yarn build` in each package and runs to completion. The output isn't useful yet, but it at least makes some of the mechanics reliable.

### CODE REVIEW

**Comment by MikeTheCanuck** [comment]
I'm not able to get as far as you @meganmckissack - can you outline the exact command sequence you used?

Here's what I've tried:

```
git clone git@github.com:DingoEatingFuzz/civic.git
cd civic
git checkout fix-all-packages
nvm use
yarn bootstrap
cd packages
cd [package-name]
yarn start
```

This yields breaking errors in emergency-response, homelesness, housing and transportation (budget runs fine) - same kinds of `component-library` errors we're seeing in #35 and #36.

When I go back to the `civic` root and run `yarn storybook` it doesn't terminate (I have to add Ctrl-C), then perform `yarn start` in one of the packages, I still get breaking errors.

When I leave the storybook server running in one `Terminal` and `yarn start` a package in another Terminal session, I still get these breaking errors.

I'm working from the monorepo README that's part of this PR.

By comparison, I'm getting all packages but emergency-response to build using the same command sequence as above (with the exception of working from Hackoregon/civic, master branch).

**Comment by DingoEatingFuzz** [comment]
@meganmckissack I haven't seen an issue building the webpacker package, so the error message would be helpful! As for the emergency-response package, I had that error, but I fixed it by adding `babel-cli` as a dependency. Can you run `yarn bootstrap` in the root and try again?

@MikeTheCanuck Unless you have something special in your gitconfig, I don't think `git checkout fix-all-packages` works there, since you don't have that branch locally. Try `git checkout origin/fix-all-packages` instead. All the other steps look good.

**Comment by MikeTheCanuck** [comment]
@DingoEatingFuzz I would've had problems performing `git checkout fix-all-packages` from the Forked project, but I was working from within your forked project in the hopes that would relieve me of having to figure out how to work from a branch-in-a-fork from the forked project.

Or is what you're saying is that I still didn't get it right - cloning your fork still doesn't give me the ability to test the specific changes you're proposing in this PR?

**Comment by DingoEatingFuzz** [comment]
Cloning the fork does give you that ability, but when you clone, all the branches on the remote don't sync to your local branches.

So the remote has branches `master` and `fix-all-packages` while your local clone only has `master`. So `git checkout fix-all-packages` probably errored with a message like `Unknown branch fix-all-packages`. But if you instead do `git checkout origin/fix-all-packages` it will look on the remote for the branch. This will succeed but will put you in detached HEAD state, which is fine for the purpose of testing.

**Comment by MikeTheCanuck** [comment]
The unsuccessful results reported above are for the `fix-all-packages` branch of the DingoEatingFuzz fork of the project:

```
$ git remote -v
origin	git@github.com:DingoEatingFuzz/civic.git (fetch)
origin	git@github.com:DingoEatingFuzz/civic.git (push)
```

## Errors from this PR
Since I wasn't explicit, here is an example of the breaking errors I'm receiving when I follow the command sequence [above](https://github.com/hackoregon/civic/pull/37#issuecomment-353926893) for the `homelesness` package:

```
ERROR in ./src/components/Definition/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/Definition'
 @ ./src/components/Definition/index.js 19:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/Migration/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/Migration'
 @ ./src/components/Migration/index.js 19:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/HomelessPopulation/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/HomelessPopulation'
 @ ./src/components/HomelessPopulation/index.js 24:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/UnaccompaniedYouth/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/UnaccompaniedYouth'
 @ ./src/components/UnaccompaniedYouth/index.js 11:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/Women/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/Women'
 @ ./src/components/Women/index.js 18:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev

ERROR in ./src/components/Services211/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/Services211'
 @ ./src/components/Services211/index.js 19:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev
```

I'm receiving similar kinds of errors when `yarn start` the **housing** and **transportation** packages, and the well-known errors from the **emergency-response** package.

## No errors from the current master
To be clear, when I run this command sequence for the upstream package (master branch), I receive none of the above-mentioned errors:

### Commands
```
git clone git@github.com:HackOregon/civic.git
cd civic
nvm use
yarn bootstrap
cd packages
cd homelesness
yarn start
```

Although I suspect there's some additional difference in development environments that isn't accounted for by the README and my outlined command sequences, at this point I cannot recommend merging a PR that appears to regress working packages.  

I'm interested in helping to troubleshoot what those differences are (and what improvements were recently merged to master that might be included in this PR), but I'm a little stumped where to begin - it appears to me that this PR's commits were added on top of the PR 24 that is the latest commit to master, but it seems hard to believe that working packages were enhanced and somehow that many were regressed.

**Comment by meganmckissack** [comment]
@MikeTheCanuck I was going through the steps again last night and after starting from scratch, so I convey the exact steps of what I was doing, I couldn't get it to work, it's something with the component library populating for the rest of the projects to use.  I could never get the projects to work from master or from the current pr of David's (even though in pr #36  it all builds successfully and the server starts, nothing shows up/errors in the console).  Before all that, I did run yarn bootstrap in this pr, @DingoEatingFuzz,  and emergency-response worked on yarn start.  I still got the webpacker errors below.  This occurs after the component library builds.

```(node:21817) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: npm run build
sh: npx: command not found

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/mmckissack/.nvm/versions/node/v6.11.4/bin/node" "/Users/mmckissack/.nvm/versions/node/v6.11.4/bin/npm" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @hackoregon/webpacker@1.0.0-alpha.1c62c05f build: `npx babel src --out-dir lib`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @hackoregon/webpacker@1.0.0-alpha.1c62c05f build script 'npx babel src --out-dir lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @hackoregon/webpacker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx babel src --out-dir lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @hackoregon/webpacker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @hackoregon/webpacker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mmckissack/Desktop/civic/packages/webpacker/npm-debug.log

> @hackoregon/webpacker@1.0.0-alpha.1c62c05f build /Users/mmckissack/Desktop/civic/packages/webpacker
> npx babel src --out-dir lib

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DingoEatingFuzz** [comment]
@meganmckissack `npx` is a [relatively new command](http://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner) that ships with npm. You probably just have to update npm and it will work.

@MikeTheCanuck Fortunately all those errors are actually the same error, so it may not be that broken. I'll try getting everything running from a clean clone. It's starting to sound like an environment issue that I don't have for some reason.

**Comment by DingoEatingFuzz** [comment]
@MikeTheCanuck from a clean clone, following your same steps, the homelessness package starts for me.

Can you run `npm ls 2>/dev/null | grep component-library`?

I get this:

```
├─┬ @hackoregon/component-library@1.0.0-alpha.1c62c05f -> /Users/michael/hacko/civic2/packages/component-library
```

**Comment by MikeTheCanuck** [comment]
I think you're on to something @DingoEatingFuzz - when I follow the same sequence on a clean clone of your fork, this is what comes out after a failing `yarn start`:

```
$ npm ls 2>/dev/null | grep component-library
├── UNMET DEPENDENCY @hackoregon/component-library@^1.0.0-alpha.1c62c05f
```

**Comment by DingoEatingFuzz** [comment]
Real strange. Maybe try going into the `component-library` package, running `yarn build`, then trying `yarn start` in a project package again? Assume `yarn build` succeeds in `component-library`.

**Comment by DavideDaniel** [comment]
Thanks Michael! I'm returning from vacation tomorrow but I was able to run this branch remotely.

**Comment by MikeTheCanuck** [comment]
@DingoEatingFuzz I've tried clean-cloning and following three different approaches to getting the `homelesness` package to run, and only one of the three has positive results:

1. Follow the README the way I've been reading it all along // failed with runtime errors
2. Add in the `yarn build` for the component library package // failed with build error
3. Add in the `yarn build` for the entire repo // success

## Follow the README the way it reads to me
Here's the command sequence I've been following each time I come to this project and follow the current README:

```
rm -rf civic
git clone git@github.com:DingoEatingFuzz/civic.git
cd civic
git checkout fix-all-packages
nvm use
yarn bootstrap
cd packages/homelesness
yarn start
```

Which results in [these kinds of errors](https://github.com/hackoregon/civic/pull/37#issuecomment-354036041) at runtime:
```
ERROR in ./src/components/Definition/index.js
Module not found: Error: Can't resolve '@hackoregon/component-library' in '/Users/mike/code/trash-repos/civic/packages/homelesness/src/components/Definition'
 @ ./src/components/Definition/index.js 19:24-64
 @ ./src/components/CardCollection/index.js
 @ ./src/index.js
 @ ./src/client.dev.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true leaflet ./src/client.dev
```

## Add yarn build for component library
Here's the command sequence I followed:

```
rm -rf civic
git clone git@github.com:DingoEatingFuzz/civic.git
cd civic
git checkout fix-all-packages
nvm use
yarn bootstrap
cd packages/component-library
yarn build
```

And the result:

```
yarn run v1.3.2
$ BABEL_ENV=esm npm run build:esm && BABEL_ENV=cjs npm run build:cjs

> @hackoregon/component-library@1.0.0-alpha.1c62c05f build:esm /Users/mike/code/trash-repos/civic/packages/component-library
> babel src --out-dir es --copy-files --no-comments

sh: babel: command not found

npm ERR! Darwin 17.3.0
npm ERR! argv "/Users/mike/.nvm/versions/node/v6.11.4/bin/node" "/Users/mike/.nvm/versions/node/v6.11.4/bin/npm" "run" "build:esm"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @hackoregon/component-library@1.0.0-alpha.1c62c05f build:esm: `babel src --out-dir es --copy-files --no-comments`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @hackoregon/component-library@1.0.0-alpha.1c62c05f build:esm script 'babel src --out-dir es --copy-files --no-comments'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @hackoregon/component-library package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir es --copy-files --no-comments
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @hackoregon/component-library
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @hackoregon/component-library
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mike/code/trash-repos/civic/packages/component-library/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Add yarn build for the repo
Here's the command sequence I followed that took me all the way to a running dev server *and* no runtime errors:

```
rm -rf civic
git clone git@github.com:DingoEatingFuzz/civic.git
cd civic
git checkout fix-all-packages
nvm use
yarn bootstrap
yarn build
cd packages/homelesness
yarn start
```

I strongly recommend a rewrite of the README, and I'll give it a shot and see if I can figure out how to append it to this PR.

**Comment by DingoEatingFuzz** [comment]
Looks like running `yarn build` for the `component-library` package _should_ have worked, but babel wasn't found:

```
yarn run v1.3.2
$ BABEL_ENV=esm npm run build:esm && BABEL_ENV=cjs npm run build:cjs

> @hackoregon/component-library@1.0.0-alpha.1c62c05f build:esm /Users/mike/code/trash-repos/civic/packages/component-library
> babel src --out-dir es --copy-files --no-comments

sh: babel: command not found
```

What we do in other packages is use `npx babel-cli <command>` and include `babel-cli` as a dev dependency so `npx` doesn't fetch the package every time. 

It must work from the root because `babel` is accessible from that context.

> I strongly recommend a rewrite of the README, and I'll give it a shot to see if I can figure out how to append it to this PR.

I'm okay with this only because the README should reflect the state of things. Just bare in mind that under working conditions, running `yarn build` from the `component-library` package should work. Potentially `yarn build` should also be incorporated in `yarn bootstrap`.

What I'm saying is once we work all the kinks out, we should make sure to update the README. We should also be striving for simplicity of setup.

**Comment by MikeTheCanuck** [comment]
I'll fire off two issues to account for the two ideas outlined by Michael:
- enable `yarn build` to work from the `component-library` directory
- incorporate `yarn build` into `yarn bootstrap`

Otherwise it looks like we're all on the same page so I'll pull the trigger.

**Pull request merged**
