### PR TITLE
New working with redux guide

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
[Link to formatted file](https://github.com/hackoregon/civic/blob/redux-guide/WORKING_WITH_REDUX.md).

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
> It wasn’t obvious to me that you needed to add the reducer for each component to the index.js file. Also the error message for this was not helpful, so might be worth adding a few words.

Yes! I definitely need to add that.

> I think an example that involved importing and doing data transformations would be more useful and realistic.

I'm not following this one. Selectors don't import anything and the example does do data transformation.

Do you have an example in mind for what the example should be?

**Comment by jaronheard** [comment]
Like this but done properly? :P

https://github.com/hackoregon/civic/blob/53bd7cae6b3c4b9f9f45ab6a0cfe8f2e7a2db0b0/packages/2018-transportation-systems/src/state/decline-in-ridership/selectors.js

In the example below you have the getFarmersMarketsOverTimeData selector. I
wanted to see how a data transformation would interact with that selector
(e.g. should it be part of the same selector? should it be a separate
selector and composed somehow?). I think if you just extended your current
example to show that it would be fantastic.
https://github.com/hackoregon/civic/blob/master/packages/2018-example-farmers-markets/src/state/farmers-markets-over-time/selectors.js

**Comment by DingoEatingFuzz** [comment]
@jaronheard I beefed up the selector examples and added a note about how reducers from ducks need to be included in the project reducer. Lemme know what you think!

**Comment by jaronheard** [comment]
@DingoEatingFuzz That looks great! Going to go ahead and merge this in.

**Pull request merged**
