### PR TITLE
Make the horizontal bar chart horizontal, and make new bar chart component

### PR DESCRIPTION
**Pull request by accua**
This PR addresses #83. It makes the horizontal bar chart, horizontal and creates a new bar chart component. This also sets up testing files for both but doesn't actually test. I don't have much experience testing JS yet, but wanted to get this up for review.

~~* Still needs tooltip, and bar highlighting on hover.~~
* Still needs tooltip font color changed to `tomato`, and tooltip-border == none

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
This looks good in that it correctly makes the HorizontalBarChart horizontal. However it introduces a new issue: we have no normal bar chart.

Do you want to extend this PR to handle both chart types in some graceful DRY way, or should I make another issue?

**Comment by accua** [comment]
@DingoEatingFuzz forgot to push up the other chart, this addresses that and adds a tooltip/some styling.

**Comment by AlexanderNull** [comment]
I thought you had copied over some tests for this

**Comment by accua** [comment]
@AlexanderNull not yet. I heard that #95 was a good place to look for a start.

@jaronheard I'm not sure, but I would imagine so. I'll do some research! I will begin working on a tooltip component unless someone else already has?

**Pull request merged**
